version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the app...
  post_build:
    commands:
      - echo Build completed!
artifacts:
  files:
    - '**/*'
  base-directory: .
